version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - yum install -y maven
  build:
    commands:
      - echo Building the application...
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username riyazsk007 --password-stdin 807034087511.dkr.ecr.us-east-1.amazonaws.com/springboot-aws-deploy
      - docker push $REPOSITORY_URI:latest
artifacts:
  files:
    - target/*.jar


